Roster/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Roster.views import RosterListView

app_name = 'wowraid'
urlpatterns=[
    #Home Page
    path('',views.home, name='home'),
    #Roster Page
    #path('rosters/',views.rosters, name='rosters'),
    path('rosters/', RosterListView.as_view(), name="rosters"),
    #Specific Roster
    path('rosters/<int:roster_id>/',views.roster, name='roster'),
    #About
    path('about/', views.about, name='about'),
    #Creating a Roster
    #path('new_roster/',views.new_roster, name='new_roster')
]
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path, include
from . import views

app_name = 'Users'
urlpatterns =[
    path('',include('django.contrib.auth.urls')),
    #Registration Path
    path('register', views.register,name='register'),
]

wowraid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import logout
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Roster.urls')),
    path('users/',include('users.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL},
    name='logout'),
]

Roster/models.py
from queue import Empty
from statistics import mode
from unicodedata import name
from django.db import models

# Enums 
class ClassTypes(models.TextChoices):
    DRUID = "Druid"
    DEATHKNIGHT = "DeathKnight"
    HUNTER = "Hunter"
    ROGUE = "Rogue"
    PALADIN = "Paladin"
    PRIEST = "Priest"
    MAGE = "Mage"
    SHAMAN = "Shaman"
    WARRIOR = "Warrior"
    WARLOCK = "Warlock"
class SpecTypes(models.TextChoices):
    #Druid
    RESTO = "Restoration"
    FERAL = "Feral"
    BALANCE = "Balance"
    #DeathKnight
    BLOOD = "Blood"
    FROST = "Frost"
    UNHOLY = "Unholy"
    #Hunter
    SURVIVAL = "Survival"
    MARKSMAN = "Marksman"
    BEAST_MASTER = "Beast Master"
    #Rogue
    COMBAT = "Combat"
    ASSASSINATION = "Assassination"
    SUBTLETY = "Subtlety"
    #Paladin
    HOLY = "Holy"
    RETRIBUTION = "Retribution"
    PROTECTION = "Protection"
    #Priest
    SHADOW = "Shadow"
    DISCIPLINE = "Discipline"
    #Mage
    FIRE = "Fire"
    Arcane = "Arcane"
    #Shaman
    ELEMENTAL = "Elemental"
    ENHANCEMENT = "Enhancement"
    #Warrior
    FURY = "Fury"
    ARMS = "Arms"
    #Warlock
    DESTRUCTION = "Destruction"
    DEMOLOGY = "Demology"
    AFFLICTION = "Affliction"
class BuffType(models.TextChoices):
    AGIL_AND_STR = "Agility and Strength"
    ARMOR_PERC = "Armor Percent"
    ATCK_POW = "Attack Power"
    ATCK_POW_PERC = "Attack Power Percent"
    HERO = "Heroism"
    DAMAGE_PERC = "Damage Percent"
    DAMAGE_REDUCT_PERC = "Damage Reduction Percent"
    HASTE_PERC = "Haste Percent"
    HEALING_REC_PERC = "Healing Recieved Percent"
    HEALTH = "Heath"
    INT = "Intellect"
    MANA_PER = "Mana Per Second"
    MELE_CRIT_PERC = "Melee Critical Percent"
    MELE_HASTE_PERC = "Melee Haste Percent"
    REPLINISH = "Replenishment"
class RoleType(models.TextChoices):
    TANK = "Tank"
    RANGED_DPS = "Ranged DPS"
    MELEE_DPS = "Melee DPS"
    HEALER = "Healer"
class FactionType(models.TextChoices):
    alliance = "Alliance"
    horde = "Horde"
    both = "Both"
# Create your models here.
class Spell(models.Model):
    spell_id = models.AutoField(primary_key = True)
    buff_name = models.CharField(max_length=200)
    buff_description = models.CharField(max_length=200)
    buff_type = models.CharField(max_length = 200, choices = BuffType.choices, default=Empty)

class Class(models.Model):
    class_id = models.AutoField(primary_key = True)
    class_name = models.CharField(max_length = 200, choices = ClassTypes.choices, default = ClassTypes.DRUID)
    spec = models.CharField(max_length = 200, choices = SpecTypes.choices, default = SpecTypes.AFFLICTION)
    buff_name = models.ForeignKey(Spell, on_delete=models.DO_NOTHING, default="", null=True)
    role = models.CharField(max_length=200, choices = RoleType.choices)

class Player(models.Model):
    player_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    classes = models.ForeignKey(Class, on_delete=models.DO_NOTHING)
    start_free_time = models.DateTimeField
    end_free_time = models.DateField

class Roster(models.Model):
    roster_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    players = models.ForeignKey(Player, on_delete = models.CASCADE)
    guild = models.CharField(max_length=200, default="N/A")
    start_time = models.DateTimeField(null = True)
    end_time = models.DateTimeField(null = True)
    realm = models.CharField(max_length=200)
    faction = models.CharField(max_length=200, choices = FactionType.choices, default = FactionType.both)

    

users/models.py
from django.db import models

# Create your models here.

Roster/forms.py
from django import forms
from .models import Roster

#class RosterForm(forms.ModelForm):
#    class Meta:
#        model = Roster
#    fields = '__all__'

Roster/views.py
from django.views.generic import ListView
from multiprocessing import context
from django.shortcuts import redirect, render
from django_tables2 import SingleTableView

from Roster.tables import RosterTable

from .models import Roster


def home(request):
    #Home Page
    return render(request,'Roster/home.html')

def rosters(request):
    #Roster Page
    rosters = Roster.objects.order_by('start_time')
    context = {'roster':rosters}
    return render(request, 'Roster/rosters.html', context)

def roster(request, roster_id):
    #Show Specific Roster
    roster = Roster.objects.get(roster_id=roster_id)
    context = {'roster':roster}
    return render(request, 'Roster/roster.html',context)

def about(request):
    return render(request, 'Roster/about.html')

class RosterListView(SingleTableView):
    model = Roster
    table_class = RosterTable
    template_name = "Roster/rosters.html"


#def new_roster(request):
#    if request.method != 'POST':
#        form = RosterForm()
#    else:
#        form = RosterForm(data=request.POST)
#        if form.is_valid:
#            form.save()
#            return redirect('Roster/rosters.html')
#    context = {'form':form}
#    return render(request, 'Roster/new_roster.html',context)
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else: 
        form = UserCreationForm(data=request.POST)
    if form.is_valid():
        new_user = form.save()
        login(request,new_user)
        return redirect('wowraid:home')
    context = {'form':form}
    return render(request, 'registration/register.html', context)

Roster/templates/column.html
<a class="btn btn-info btn-sm" href="{% url 'wowraid:roster' record.roster_id %}">View</a>

Roster/templates/roster/about.html
{%extends "Roster/base.html"%}
{%block content%}
    <p> About WoW Roster </p>
    <p> Created by...</p>
{%endblock content%}

Roster/templates/roster/base.html
{% load static %}
<html>
    <head>
        <title>
            WoWRosters
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>        
        {% include 'Roster/navbar.html' %}
        {% block content %}   
        {% endblock %}
        {%include 'Roster/footer.html'%}
    </body>

</html>

Roster/templates/roster/footer.html
<style>
.footer-container {
    background-color: #343a40;
    padding: 4rem 0 2rem 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.footer-container > p{
    color: #fff;
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
}
</style>
<div class = "footer-container">
    <p>©Ragnaroster 2022</p>
</div>

Roster/templates/roster/home.html
{%extends "Roster/base.html"%}
{%load static%}

{%block content%}
<head>
    <link rel="stylesheet" href="{%static '/css/home.css'%}"  type="text/css"/>
</head>
    <div class = "introduction-container">
        <h1> Ragnaroster </h1>
        <p> Create and easily maintain your WoW raid team.</p>
    </div>
    <div class = "content-containter">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget iaculis urna. Morbi bibendum porttitor sollicitudin. Nullam nunc arcu, fermentum porttitor elit ut, aliquam tempus ante. Suspendisse sit amet elit eros. Integer id orci arcu. Proin ac lacus justo. Donec sagittis metus vel purus sodales vestibulum.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce efficitur turpis sed urna aliquet blandit. Vivamus euismod tortor quis diam luctus sollicitudin. Maecenas pharetra malesuada imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vel feugiat nibh. Etiam ullamcorper elementum arcu, 
sed malesuada eros rutrum eu. Vestibulum sit amet justo rutrum, gravida erat ut, dignissim dui. Maecenas id dignissim turpis. Phasellus odio lorem, gravida non ornare at, ornare nec ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
<div class = "row">
    <div class = "column"> <p> something </p> </div>
    <div class = "column"> Something 2 </div>
    <div class = "column"> Something 3 </div>
</div>
</div>
{%endblock content%}

Roster/templates/roster/navbar.html
{% load static %}
 
<style>
  .greet{
    font-size: 16px;
    color: #fff;
    margin-right: 20px;
    align: "middle";
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style = "position: fixed; width = 100%">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li>
        <img src = "{%static '/images/logoR1.png'%}" alt="logo" align="center" width="40" height="40">
    </li>   
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'wowraid:home' %}">Home</a>
      </li>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'wowraid:rosters' %}">Rosters</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'wowraid:about' %}">About</a>
      </li>
    </ul>
  </div>
    {%if user.is_authenticated%}
    <span>
      <a class = "greet" href="{%url 'Users:login'%}">Hello, {{user.username}}. </a>
    </span>
    <span>
      <a class="greet" href="{% url 'Users:logout' %}">Logout</a>
    </span>
    {%endif%}
    <span>
    <a class="btn btn-primary" href="{%url "social:begin" "battlenet-oauth2"%}">
      <img src="{%static '/images/battlenet.png'%}" alt="" width="30" height="30"> Log In</a>
   <!-- <a class = "greet" href="{% url 'Users:login'%}">Log in</a> -->
    </span>

</nav>

Roster/templates/roster/new_roster.html
{%extends "Roster.base.html%"%}

{%block content%}
<p> Add a new roster:</p>
<form action="{% url 'wowraid:new_roster.html'%}" method='post'>
    {%csrf_token%}
    {{form.as_p}}
    <button name = "submit"> Add Roster </button></form>

{%endblock content%}

Roster/templates/roster/roster.html
{%extends "Roster/base.html"%}

{%block content%}

<p>{{roster.name}}</p>

{%endblock content%}

Roster/templates/roster/rosters copy.html
{%extends "Roster/base.html"%}
{%load static%}

{%block content%}
<head>
    <link rel="stylesheet" href="{%static '/css/roster.css'%}"  type="text/css"/>
</head>

<div class = "introduction-container">
    <h1> Rosters </h1>
</div>
    <table class = "roster-table">
        <tr style="">
            <th> Roster Name </th>
            <th> Start Time </th>
            <th> End Time </th>
            <th> Guild </th>
        </tr>
        {% for r in roster%}
        {%if r.faction == "Horde"%}
            <tr style = "background-color: #ff0000">
        {%elif r.faction == "Alliance"%}
            <tr style = "background-color: blue">
        {%else%}
            <tr style = "background-color: #008000">
        {%endif%}
                <td>
                    <a href="{% url 'wowraid:roster' r.roster_id%}">{{ r.name }}</a>
                </td>
                <td>
                    {{r.start_time}} 
                </td>
                <td>
                    {{r.end_time}}
                </td>
                {%if r.guild == ""%}
                <td>
                    N/A
                </td>
                {%else%}
                <td>
                    {{r.guild}}
                </td>
                {%endif%}
            </tr>
            {%empty%}
                <li> No Rosters have been added </li>
        {%endfor%}
        </table>
{%endblock content%}

Roster/templates/roster/rosters.html
{%extends "Roster/base.html"%}
{%load render_table from django_tables2%}
{%load static%}

{%block content%}
<head>
    <link rel="stylesheet" href="{%static '/css/roster.css'%}"  type="text/css"/>
</head>

<div class = "introduction-container">
    <h1> Rosters </h1>
</div>

<body>
    {%render_table table%}
{%endblock content%}